version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: emargement-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emargement
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
